
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Title: Laplace's Equation, Potential and Fields Two Parallel Plates
 * Date: 14 May 2023
 *  * @author ART2023
 */
public class PotentialFieldNearCharge extends javax.swing.JFrame {

    /**
     * Creates new form PotentialField
     */
    public PotentialFieldNearCharge() {
        initComponents();
    }
    double w[][] = new double [7][7];
    private double [][] initilizePointMesh(){
    double v0[][]={{-1.0, -0.67, -0.33, .00, 0.33, 0.67, 1.00},
                   {-1.0,  0.00,  0.00, .00, 0.00, 0.00, 1.00},
                   {-1.0,  0.00,  0.00, .00, 0.00, 0.00, 1.00},
                   {-1.0,  0.00,  0.00, .00, 0.00, 0.00, 1.00},
                   {-1.0,  0.00,  0.00, .00, 0.00, 0.00, 1.00},
                   {-1.0,  0.00,  0.00, .00, 0.00, 0.00, 1.00},
                   {-1.0, -0.67, -0.33, .00, 0.33, 0.67, 1.00}
    };
    double wall [][]={{1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1},
                      {1,0,0,0,0,0,1}};
    w=wall;
    return v0;
    }
    //Urusan File
public PrintStream openfile (String filename){
PrintStream ps = null;
try{
ps = new PrintStream (new FileOutputStream(filename));
}catch (IOException e){
    System.err.printf("\nProblem creating file:%s\n\n",filename);}
return ps;
}
public void savaData(String namafail,javax.swing.JTextArea txtOutput){
PrintStream ps = openfile(namafail);
String dataStr = txtOutput.getText();
ps.print(dataStr);
ps.close();

}



public void callGnuplot(javax.swing.JTextArea gnuPlotCmd){
        PrintStream ps = openfile("gnuplotcmd.plt");
        String strCmd = gnuPlotCmd.getText();
        ps.printf("%s\n", strCmd);
        ps.close();

        Runtime callgp = Runtime.getRuntime();
        try {
           //Process prcs = callgp.exec("D:\\Pengajaran\\2022_2023_SEM2\\NetBean Projects\\PotentialFields -persist gnuplotcmd.plt");
            Process prcs = callgp.exec("wgnuplot gnuplotcmd.plt");
        } catch (IOException e) {
           System.err.println ("Error calling gnuplot");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calculateButton1 = new javax.swing.JButton();
        PlotButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gnuPlotCmd = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContour = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_Efield = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_gnuplot_Efield = new javax.swing.JTextArea();
        button_plot_Efield = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("POTENTIAL AND FIELDS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("<html>\n<table>\n<tr>\n&part<sup>2</sup> V    <t></t> <t></t> <t></t> <t></t> &part<sup>2</sup> V   <t></t> <t></t> <t></t> <t></t>      &part<sup>2</sup> V\n</tr>\n<tr>\n.......  <t></t>     + .......  <t></t> +  .......  =   0\n</tr>\n<tr>\n&part x <sup>2</sup>  <t></t> <t></t> <t></t> <t></t>    &part y <sup>2</sup>      <t></t> <t></t> <t></t> <t></t>     &part z <sup>2</sup>\n</tr>\n\n</table>\n</html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Laplace's Equation");

        calculateButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculateButton1.setText("Calculate");
        calculateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButton1ActionPerformed(evt);
            }
        });

        PlotButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlotButton1.setText("Plot");
        PlotButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(calculateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(PlotButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlotButton1)
                    .addComponent(calculateButton1))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Main", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Output", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        gnuPlotCmd.setColumns(20);
        gnuPlotCmd.setRows(5);
        gnuPlotCmd.setText("reset\n\nset contour\nsplot \"data.dat\" with line\n\npause -1");
        jScrollPane2.setViewportView(gnuPlotCmd);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plot", jPanel3);

        txtContour.setColumns(20);
        txtContour.setRows(5);
        jScrollPane3.setViewportView(txtContour);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ContourPlot", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 255, 0));

        ta_Efield.setBackground(new java.awt.Color(255, 255, 255));
        ta_Efield.setColumns(20);
        ta_Efield.setRows(5);
        jScrollPane5.setViewportView(ta_Efield);

        ta_gnuplot_Efield.setColumns(20);
        ta_gnuplot_Efield.setRows(5);
        ta_gnuplot_Efield.setText("reset\n\nplot \"Efield.dat\" u 1:2:3:4 w vector\n\npause -1");
        jScrollPane6.setViewportView(ta_gnuplot_Efield);

        button_plot_Efield.setText("plot efield");
        button_plot_Efield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plot_EfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_plot_Efield)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(button_plot_Efield)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("E field", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    This program we want to calculate the electric potential and field lines 
    between two parallel plates use Jacobi Method
    */
    private void calculateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButton1ActionPerformed
    int max =7;
    int n = 100;
    double v[][]= initilizePointMesh();
    calculate(v,max,n);
    E_field(v);
    savaData("data.dat",txtContour);
    savaData("Efield.dat",ta_Efield);
    }//GEN-LAST:event_calculateButton1ActionPerformed

    private void PlotButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotButton1ActionPerformed
       callGnuplot(gnuPlotCmd);
    }//GEN-LAST:event_PlotButton1ActionPerformed

    private void button_plot_EfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plot_EfieldActionPerformed
        callGnuplot(ta_gnuplot_Efield);
    }//GEN-LAST:event_button_plot_EfieldActionPerformed
    /*
        v[][] - the potential, 
        max - determines number of grid steps
        n- number of iterations of relaxation algorithm
    */
    
    public void calculate(double [][]v,int max,int n){
        double vtemp [][] = new double [max][max];
        int i,j;
        for(i=0;i<max;i++){
          for(j=0;j<max;j++){
          vtemp[i][j]=v[i][j];
          }}
        int r =0;
        double diff = 1000000;  //any big number
        //update
        do{
        r++;
        diff=update(v,vtemp,max);
        diff=update(vtemp,v,max);
        }while(r<=n&&diff>1e-4);
        outputMatrix(r,v);
        outputContour(v);
    }
    public double update(double v1[][], double v2[][],int max){
    double diff=0;
    double temp =0;
    for(int i=1;i<max-1;i++){
       for(int j=1;j<max-1;j++){
       temp = v1[i][j];
       if(w[i][j]==0){
        v2[i][j]=(v1[i-1][j]+v1[i+1][j]+v1[i][j-1]+v1[i][j+1])/4.0;
       }
       diff = diff+Math.abs(temp-v2[i][j]);
    }
    }
    diff = diff/Math.pow((max+1),2.0);
    return diff;
    }
    //method to display result
    public void outputMatrix(int rr, double v[][]){
    txtOutput.append("#after "+rr+" call to update \n");
    int max = v.length;
      for(int i=0;i<max;i++){
          for(int j =0;j<max;j++){
           String str = String.format(" %.2f ", v[i][j]);
           txtOutput.append(str);
          }
          txtOutput.append("\n");
      }
    txtOutput.append("\n");
    }
    public void outputContour(double v[][]){
    double x,y,delx,dely;
    int max = v.length;
    y =1.0;
    delx = 2.0/6.0;
    dely = 2.0/6.0;
       for(int i =0;i<max;i++){
       x =-1;
          for(int j =0;j<max;j++){
          String str = String.format(" %.2f %.2f %.2f\n",x,y,v[i][j]);
          txtContour.append(str);
          x=x+delx;
          }
       txtContour.append("\n");
         y = y-dely;
       }
            txtContour.append("\n");
    }
    
    public void E_field(double v[][]){
        int max = v.length;
        double delx=2.0/8.0, dely=2.0/8.0;
        double Ex[][] = new double[max+1][max+1];
        double Ey[][] = new double[max+1][max+1];
        double x = -1.0, y = 1.0;
             for(int i=1;i<max-1;i++){
         x=-1.0;   
        for(int j=1;j<max-1;j++){
            Ex[i][j]= -((v[i+1][j]-v[i-1][j])/2*delx);
            Ey[i][j]= -((v[i][j+1]-v[i][j-1])/2*dely);
            String str1 = String.format(" %.2f %.2f %.2f %.2f\n",
            x,y,Ey[i][j]/2, -Ex[i][j]/2 );
            x = x+delx;
            ta_Efield.append(str1);
            }
        ta_Efield.append("\n");
        y=y-dely;
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PotentialFieldNearCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PotentialFieldNearCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PotentialFieldNearCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PotentialFieldNearCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PotentialFieldNearCharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlotButton1;
    private javax.swing.JButton button_plot_Efield;
    private javax.swing.JButton calculateButton1;
    private javax.swing.JTextArea gnuPlotCmd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea ta_Efield;
    private javax.swing.JTextArea ta_gnuplot_Efield;
    private javax.swing.JTextArea txtContour;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
